title: whoisrealminjueun?
name: whoisrealminjueun?
description: >- # this means to ignore newlines until "baseurl:"
keywords: [Your keywords]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whoisrealminjueun.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
language: en
timezone: Asia/Seoul

analytics:   # the Google Analytics property ID, e.g. UA-XXXXX-Y

paginate: 25
paginate_path: "/page:num/"

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: compressed

collections:
  blogposts:
    output: true
    permalink: /_blogposts/
  docs:
    output: true
    permalink: /_search/

# Category settings
category archive:
  type: liquid
  path: /category
  
jekyll-archives:
  enabled: 
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
    
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

      # Begin encryption code.
      # This portion of the build job was written by Evan Baldonado (EvanBaldonado.com). Please do not remove this comment.
      # Note: this only encrypts .html pages and not any of the corresponding assets.
      - name: Encrypt pages with PageCrypt
        run: |
          npm i -D pagecrypt
          cat _protected_pages.txt | while read file password;
          do
            sudo npx pagecrypt "_site/$file" "_site/$file" "$password"
          done
      # End encryption code.
