 # Begin encryption code.
      # This portion of the build job was written by Evan Baldonado (EvanBaldonado.com). Please do not remove this comment.
      # Note: this only encrypts .html pages and not any of the corresponding assets.
      - name: Encrypt pages with PageCrypt
        run: |
          npm i -D pagecrypt
          cat _protected_pages.txt | while read file password;
          do
            sudo npx pagecrypt "_site/$file" "_site/$file" "$password"
          done
      # End encryption code.
